Game.create()

Skeleton.create(game_id: 1, name: "Cráneo", image:"/images/rayosx.jpg", skeleton_img: "")
Skeleton.create(game_id: 1, name: "Columna Vertebral", image:"/images/esqueleto-grupo.jpg", skeleton_img: "")
Skeleton.create(game_id: 1, name: "Parte Torácica", image:"/images/rayosx3.jpg", skeleton_img: "")
Skeleton.create(game_id: 1, name: "Extremidades Superiores", image:"/images/rayosx2.jpeg", skeleton_img: "")
Skeleton.create(game_id: 1, name: "Extremidades Inferiores", image:"/images/esqueletos.jpg", skeleton_img: "")

Bone.create(skeleton_id: 1, name:"Frontal")
Bone.create(skeleton_id: 1, name:"Occipital")
Bone.create(skeleton_id: 1, name:"Parietal")
Bone.create(skeleton_id: 1, name:"Temporal")
Bone.create(skeleton_id: 1, name:"Esfenoide")
Bone.create(skeleton_id: 1, name:"Etnoide")
Bone.create(skeleton_id: 1, name:"Hueso nasal")
Bone.create(skeleton_id: 1, name:"Vomer")
Bone.create(skeleton_id: 1, name:"Lacrimal")
Bone.create(skeleton_id: 1, name:"Cornetes")
Bone.create(skeleton_id: 1, name:"Malar")
Bone.create(skeleton_id: 1, name:"Maxilar superior")
Bone.create(skeleton_id: 1, name:"Mandíbula")
Bone.create(skeleton_id: 1, name:"hioides")